### ISSUE TITLE
Cannot build with OCaml 4.09 !

### ISSUE THREAD

**Issue by kBncbb** [dbuenzli/uunf#13]
My output :

![image](https://user-images.githubusercontent.com/39031553/87389596-4ff6b500-c5a7-11ea-97ab-25c72e42b7ca.png)

uunf needed for Geneweb.

Thanks for help !

**Comment by dbuenzli** [comment]
It seems the compiler got exited by your os. I also see this `linux/armx64`. Is that a small computer like an rpi by any chance ? I suspect you are running in out of memory. 

If this is on `raspbian` use these [these instructions](https://raspberrypi.stackexchange.com/questions/70/how-to-set-up-swap-space#1605) to increase the swap size.

**Comment by kBncbb** [comment]
You guessed everything...

Merci pour le coup de main, c'était bien cela. C'est un Raspberry sous Ubuntu. L'étape est passée, mais j'ai maintenant une erreur de compilation dans le code, pour un défaut de syntaxe.

Thank you very much !

**Comment by dbuenzli** [comment]
C'est un plaisir. Bonne chance pour la suite !
