### ISSUE TITLE
The build system requires updating

### ISSUE THREAD

**Issue by murmour** [dbuenzli/uunf#2]
Hello, Daniel!

Your "pkg" facility needs to be updated to the same version of it as in `uucp`, otherwise build process fails on Cygwin/MinGW-w64 (it attempts to produce `.lib` files instead of `.a` files).

On a side note, the related `uucp`, `uuseg`, and `uutf` packages do build, install, and work just great on Windows. Thank you for these libraries -- I make great use of them!

**Comment by dbuenzli** [comment]
I guess this is because of https://github.com/dbuenzli/topkg/issues/11. I'm soon going to work on an overhaul of topkg so that the system is distributed are as a library rather than embedded in the packages. This will avoid these situations.

**Comment by dbuenzli** [comment]
Would you like a pin fix ?

**Comment by murmour** [comment]
Understood. Thank you!

By the way, have you considered bundling all those `uu*` packages into a single meta-package, the building of which would produce several independent library binaries? Perhaps it would help to reduce the rather annoying packaging noise?

**Comment by murmour** [comment]
> Would you like a pin fix ?

Well, that's what I'm doing right now (using a pinned local package with an updated version of `topkg`), so the fix is not urgent.

**Comment by dbuenzli** [comment]
The build system was updated to `topkg` in f41d6f2629d85fb0e4

**Comment by murmour** [comment]
Thank you! A release on OPAM would be appreciated.

**Comment by dbuenzli** [comment]
Yes, it's coming !
