### ISSUE TITLE
Trouble building: Unbound module Uunf_data

### ISSUE THREAD

**Issue by SnarkBoojum** [dbuenzli/uunf#21]
I'm trying to package uunf for Debian, and I'm hitting the error below.

My build line is:
```
ocaml pkg/pkg.ml build --with-cmdliner true --with-uutf true
```
and the end of the build log is:
```
ocamlfind ocamldep -modules src/uunf.mli > src/uunf.mli.depends
ocamlfind ocamlc -c -g -bin-annot -safe-string -I src -I test -I support -o src/uunf.cmi src/uunf.mli
ocamlfind ocamlopt -c -g -bin-annot -safe-string -I src -I test -I support -o src/uunf_tmap.cmx src/uunf_tmap.ml
ocamlfind ocamlopt -c -g -bin-annot -safe-string -I src -I test -I support -o src/uunf_tmapbool.cmx src/uunf_tmapbool.ml
ocamlfind ocamlopt -c -g -bin-annot -safe-string -I src -I test -I support -o src/uunf_tmapbyte.cmx src/uunf_tmapbyte.ml
ocamlfind ocamlopt -c -g -bin-annot -safe-string -I src -I test -I support -o src/uunf.cmx src/uunf.ml
+ ocamlfind ocamlopt -c -g -bin-annot -safe-string -I src -I test -I support -o src/uunf.cmx src/uunf.ml
File "src/uunf.ml", line 38, characters 39-65:
38 | let nfc_boundary u = Uunf_tmapbool.get Uunf_data.nfc_boundary_map u
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Uunf_data
Command exited with code 2.
pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
     '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
     'README.md' 'src/uunf.a' 'src/uunf.cmxs' 'src/uunf.cmxa' 'src/uunf.cma'
     'src/uunf.cmx' 'src/uunf.cmi' 'src/uunf.mli' 'src/uunf_data.cmx'
     'src/uunf_tmapbyte.cmx' 'src/uunf_tmapbool.cmx' 'src/uunf_tmap.cmx'
     'src/uunf_fmt.cmx' 'src/uunf_string.a' 'src/uunf_string.cmxs'
     'src/uunf_string.cmxa' 'src/uunf_string.cma' 'src/uunf_string.cmx'
     'src/uunf_string.cmi' 'src/uunf_string.mli' 'test/unftrip.native'
     'doc/index.mld' 'DEVEL.md' 'test/examples.ml']: exited with 10
```
I must be missing something obvious...

**Comment by dbuenzli** [comment]
See https://github.com/dbuenzli/uunf/blob/master/DEVEL.md

**Comment by dbuenzli** [comment]
> I'm trying to package uunf for Debian,

Note you should use the distribution tarballs it has the generated data.

**Comment by SnarkBoojum** [comment]
Well, I'm supposed to package using sources, so pre-generated stuff is out.

**Comment by SnarkBoojum** [comment]
Thanks for your quick answer -- I had indeed missed something obvious!

(Notice the typo 'New unicod release' in DEVEL.md).

**Comment by dbuenzli** [comment]
I don't understand. Doesn't debian package from tarballs ? 
The sources of a release are published [here](https://erratique.ch/software/uunf/releases/).

**Comment by SnarkBoojum** [comment]
Sources means what developers use, so I should use as little pre-built stuff as possible.

**Comment by dbuenzli** [comment]
> Sources means what developers use, so I should use as little pre-built stuff as possible.

Nothing is pre-built, sources are being generated. In general it's unwise to package from my repos. A function is applied on the sources to generate the source tarballs. 

I'm still confused about what you are saying, the [upstream tarballs](https://wiki.debian.org/Packaging/Intro#Three_central_concepts) are in the directory I pointed you to.
