### ISSUE TITLE
Dune

### ISSUE THREAD

**Issue by tacerus** [dbuenzli/uunf#23]
Hi,

it seems uunf is currently only buildable using the legacy OCamlbuild. It would be great if support for Dune could be considered for a future release.

Best,
Georg

**Comment by tacerus** [comment]
I mix up OCamlbuild and topkg, and notice you being the maintainer of topkg. Hence I think my request is unreasonable. :-)

**Comment by dbuenzli** [comment]
Some people maintain overlays `dune` overlays [here](https://github.com/dune-universe/opam-overlays/tree/master/packages), maybe that can satisfy you.

**Comment by tacerus** [comment]
Interesting, thank you for the pointer!
