### ISSUE TITLE
NFKC form incorrectly distinguishes two compatibility-equivalent strings

### ISSUE THREAD

**Issue by stedolan** [dbuenzli/uunf#8]
[UAX #15](http://unicode.org/reports/tr15/) specifies that [`toNFKC(x) = toNFKC(toNFD(x))`](http://unicode.org/reports/tr15/#Design_Goals) - since `x` and `toNFD(x)` are canonically equivalent, they should also be compatibility equivalent and have the same NFKC form.

The sequence:

    U+ff80 U+1fd3 U+ff9e U+1fd3

is normalised to form `NFD` by uunf as:

    U+ff80 U+3b9 U+308 U+301 U+ff9e U+3b9 U+308 U+301

and normalised to form `NFKC` as:

    U+30c0 U+390 U+390

However, when the `NFD` form above is further normalised to form `NFKC`, `uunf` produces the following output, which differs from the `NFKC` form above:

    U+30bf U+390 U+3099 U+390

(I found this example using [crowbar](https://github.com/stedolan/crowbar). The full testcase is [here](https://github.com/stedolan/crowbar/blob/master/examples/test_uunf.ml))

**Comment by stedolan** [comment]
I left the fuzzing job running for longer, and it found [some more cases](https://gist.github.com/stedolan/6ea03935221d31e7786c49b8854aef02). The simplest one seems to be this:

    [U+1c6 U+32d "ǆ̭"]

when normalised to form NFKD and then to form NFKC gives the correct (I think) NFKC form:

    [U+64 U+17e U+32d "dž̭"]

However, if it's normalised to NFKC directly, then the `COMBINING CIRCUMFLEX ACCENT BELOW` gets incorrectly moved past the `z` and attaches to the `d`:

    [U+1e13 U+17e "ḓž"]

**Comment by dbuenzli** [comment]
Thanks for the reduction. There was a bug in the (terrible) implementation of the canonical composition algorithm. This was rewritten more cleanly and hopefully correctly in 9459c907e84eb9feaf3701ba48bf632c0eb801a0
